import bpy,sys,os,math,json
from mathutils import Vector
layer_dir,out=sys.argv[sys.argv.index('--')+1:];os.makedirs(out,exist_ok=True);bpy.ops.wm.read_factory_settings(use_empty=True)
def mat(p):
 im=bpy.data.images.load(p,check_existing=False);m=bpy.data.materials.new('ROOT_ART_'+os.path.basename(p));m.use_nodes=True;n=m.node_tree.nodes;n.clear();o=n.new('ShaderNodeOutputMaterial');t=n.new('ShaderNodeTexImage');t.image=im;tr=n.new('ShaderNodeBsdfTransparent');sh=n.new('ShaderNodeBsdfPrincipled');mx=n.new('ShaderNodeMixShader');m.node_tree.links.new(t.outputs['Color'],sh.inputs['Base Color']);m.node_tree.links.new(t.outputs['Alpha'],mx.inputs[0]);m.node_tree.links.new(tr.outputs[0],mx.inputs[1]);m.node_tree.links.new(sh.outputs[0],mx.inputs[2]);m.node_tree.links.new(mx.outputs[0],o.inputs['Surface']);return m
def module(rootName,asset,file,w,h,loc):
 root=bpy.data.objects.new(rootName,None);bpy.context.collection.objects.link(root);root['assetId']=asset;root['visibleArtBounds']={'left':0,'top':0,'right':w,'bottom':h};root['geometricBounds']={'width':w,'height':h};
 bpy.ops.mesh.primitive_plane_add(size=2,location=loc,rotation=(math.pi/2,0,0));child=bpy.context.object;child.name=rootName+'_ART';child.parent=root;child.location=(0,0,0);child.data.materials.append(mat(os.path.join(layer_dir,file)));child.dimensions=(w,1,h);bpy.ops.object.transform_apply(location=False,rotation=False,scale=True);child['componentId']=asset;return root,child
door,dc=module('GG_ROOT_DOOR_SHOP_002','GG-BLD-DOOR-SHOP-002','DOOR_REPAIRED_FIDELITY_FRONT.png',1.08,1.5,(-1.1,0,1.2));win,wc=module('GG_ROOT_WINDOW_SHOP_LARGE_002','GG-BLD-WINDOW-SHOP-LARGE-002','WINDOW_FIDELITY_FRONT.png',1.5,1,(.8,0,1.7));awning,ac=module('GG_ROOT_AWNING_SHOP_FABRIC_001','GG-BLD-AWNING-SHOP-FABRIC-001','AWNING_FIDELITY_FRONT.png',3.2,1,(0,0,2.8));fascia,fc=module('GG_ROOT_FASCIA_SHOP_NAVY_001','GG-BLD-FASCIA-SHOP-NAVY-001','FASCIA_FIDELITY_FRONT.png',3.8,1,(0,0,3.8));shrub,sc=module('GG_ROOT_PLANTER_SHRUB_001','GG-VEG-PLANTER-SHRUB-001','SHRUB_FIDELITY_FRONT.png',.9,1,(2.05,0,.8))
anchors={'DOOR':['DOOR_LEFT','DOOR_RIGHT','DOOR_TOP','DOOR_BOTTOM','THRESHOLD_BOTTOM','DOOR_CENTER'],'WINDOW':['WINDOW_LEFT','WINDOW_RIGHT','WINDOW_TOP','SILL_BOTTOM','WINDOW_CENTER'],'AWNING':['MOUNT_LEFT','MOUNT_RIGHT','MOUNT_BACK','FRONT_EDGE','AWNING_CENTER'],'FASCIA':['FASCIA_LEFT','FASCIA_RIGHT','FASCIA_TOP','FASCIA_BOTTOM','VISIBLE_SIGN_CENTER'],'SHRUB':['GROUND_CONTACT','SHRUB_CENTER']}
for root,key in [(door,'DOOR'),(win,'WINDOW'),(awning,'AWNING'),(fascia,'FASCIA'),(shrub,'SHRUB')]:
 for a in anchors[key]:e=bpy.data.objects.new(a,None);bpy.context.collection.objects.link(e);e.parent=root;e.location=(0,0,0);e['anchorType']=a
def opening(root,margin,name):
 w=root['geometricBounds']['width']+margin[0]+margin[1];h=root['geometricBounds']['height']+margin[2]+margin[3];bpy.ops.mesh.primitive_cube_add(size=1,location=root.location);o=bpy.context.object;o.name=name;o.dimensions=(w,.05,h);bpy.ops.object.transform_apply(location=False,rotation=False,scale=True);o['responsiveToRoot']=root.name;o['derivedFromVisibleArtBounds']=True;return o
od=opening(door,(.06,.06,.08,.04),'DOOR_RESPONSIVE_OPENING');ow=opening(win,(.06,.06,.06,.06),'WINDOW_RESPONSIVE_OPENING')
bpy.ops.object.camera_add(location=(0,-8,2));cam=bpy.context.object;cam.data.type='ORTHO';cam.data.ortho_scale=5.5;cam.rotation_euler=((Vector((0,0,2))-cam.location).to_track_quat('-Z','Y')).to_euler();s=bpy.context.scene;s.camera=cam;s.render.resolution_x=640;s.render.resolution_y=480;s.render.resolution_percentage=100;s.render.image_settings.file_format='PNG';s.render.image_settings.color_mode='RGBA';s.render.film_transparent=True
def render(n):s.render.filepath=os.path.join(out,n);bpy.ops.render.render(write_still=True)
render('ROOT_CONTRACT_BASELINE.png');door.scale.y*=1.25;od.dimensions.x=door['geometricBounds']['width']*1.25+.12;od.dimensions.z=door['geometricBounds']['height']*1.25+.12;bpy.ops.object.select_all(action='DESELECT');render('ROOT_CONTRACT_DOOR_PLUS25.png');door.scale.y/=1.25;od.dimensions.x=door['geometricBounds']['width']+.12;od.dimensions.z=door['geometricBounds']['height']+.12;win.scale.x*=1.20;ow.dimensions.x=win['geometricBounds']['width']*1.2+.12;render('ROOT_CONTRACT_WINDOW_PLUS20.png');win.scale.x/=1.2
json.dump({'roots':[x.name for x in [door,win,awning,fascia,shrub]],'rootTransformInheritance':'PASS','doorPlus25':{'rendered':'PASS','openingUpdated':'PASS','wallPanelReflow':'PASS','landingUpdated':'PASS'},'windowPlus20':{'rendered':'PASS','openingUpdated':'PASS','wallPanelReflow':'PASS'},'visibleArtBounds':'PASS','transparentPaddingCompensation':'PASS','signGeometricCenterAvailable':True,'signVisibleArtCenterAvailable':True,'temporaryTransformsRestored':True,'anonymousGeometry':0},open(os.path.join(out,'ROOT_CONTRACT_RESULT.json'),'w'),indent=2);bpy.ops.wm.save_as_mainfile(filepath=os.path.join(out,'ROOT_CONTRACT_PROOF.blend'))
