import bpy,os,sys,json,math
from mathutils import Vector
out=sys.argv[sys.argv.index('--')+1];os.makedirs(out,exist_ok=True);P={'brown':(.34,.16,.09,1),'gray':(.25,.25,.25,1),'teal':(.03,.30,.38,1),'plum':(.42,.08,.32,1),'navy':(.04,.07,.20,1),'cream':(.72,.58,.40,1),'green':(.18,.38,.12,1)}
def mat(n,c):m=bpy.data.materials.new(n);m.diffuse_color=c;return m
def build(a,k):
 bpy.ops.wm.read_factory_settings(use_empty=True);M={x:mat('PRECISION_'+x.upper(),y) for x,y in P.items()};o=[]
 def q(n,d,l,c,ma):
  bpy.ops.mesh.primitive_cube_add(size=1,location=l);z=bpy.context.object;z.name=n;z.dimensions=d;bpy.ops.object.transform_apply(location=False,rotation=False,scale=True);z.data.materials.append(M[ma]);z['assetId']=a;z['assetVersion']='4.0.0';z['moduleId']=a;z['moduleVersion']='4.0.0';z['componentId']=c;z['layer']='LAYER_A_MODULE';o.append(z)
 if k=='awning':
  q('CANOPY',(3.5,1.4,.3),(0,0,.2),'AWNING','plum');q('UNDERSIDE',(3.35,1.1,.12),(0,-.15,.02),'AWNING','navy')
  for i in range(8):q('SCALLOP_%02d'%i,(.42,.22,.42),(-1.47+i*.42,-.78,-.08),'AWNING','plum')
  q('BRACKET_L',(.12,.3,1),(-1.45,-.35,-.3),'SUPPORT','cream');q('BRACKET_R',(.12,.3,1),(1.45,-.35,-.3),'SUPPORT','cream')
 elif k=='window':q('OUTER_FRAME',(2.7,.34,3.0),(0,0,1.5),'WINDOW','cream');q('INNER_FRAME',(2.35,.16,2.65),(0,-.2,1.5),'WINDOW','cream');q('GLASS',(2.05,.08,2.35),(0,-.3,1.5),'WINDOW','teal');q('SILL',(2.9,.45,.22),(0,-.22,.0),'SILL','cream');q('SHELF',(1.5,.5,.12),(0,-.35,1.0),'DISPLAY','brown')
 elif k=='fascia':q('CAP',(4.8,1.0,.25),(0,0,2.0),'FASCIA','navy');q('FASCIA',(4.6,.8,.8),(0,0,1.55),'FASCIA','navy');q('RECESS',(3.2,.18,.55),(0,-.5,1.55),'SIGN','navy');q('BORDER',(3.45,.12,.10),(0,-.62,1.55),'TRIM','cream');q('CORNICE',(4.9,1.1,.12),(0,0,2.48),'FASCIA','cream')
 elif k=='door':q('FRAME',(1.4,.3,3.6),(0,0,1.8),'DOOR','cream');q('SLAB',(1.1,.18,3.25),(0,-.2,1.8),'DOOR','brown');q('GLASS',(.62,.08,1.1),(0,-.32,2.45),'GLASS','teal');q('PANEL',(.7,.08,.55),(0,-.32,1.1),'PANEL','brown');q('KNOB',(.14,.12,.14),(.4,-.4,1.9),'HANDLE','cream');q('MAIL',(.3,.08,.08),(0,-.4,1.45),'MAIL','cream');q('THRESHOLD',(1.55,.5,.14),(0,-.1,.08),'THRESHOLD','gray')
 else:q('PLANTER',(1.2,.8,.6),(0,0,.3),'PLANTER','green');q('RIM',(1.35,.9,.14),(0,0,.62),'PLANTER','green');q('LOW',(1.0,.6,.7),(-.18,0,1.0),'SHRUB','green');q('MID',(.75,.5,.9),(.2,0,1.25),'SHRUB','green');q('HIGH',(.48,.42,1.2),(-.02,0,1.55),'SHRUB','green')
 d=os.path.join(out,a+'@4.0.0');os.makedirs(d,exist_ok=True);s=bpy.context.scene;s.render.resolution_x=512;s.render.resolution_y=384;s.render.image_settings.file_format='PNG';s.render.image_settings.color_mode='RGBA';s.render.engine='BLENDER_WORKBENCH';s.display.shading.light='STUDIO';s.display.shading.color_type='MATERIAL';bpy.ops.object.camera_add(location=(0,-12,1.5));c=bpy.context.object;c.data.type='ORTHO';c.data.ortho_scale=4.5;c.rotation_euler=((Vector((0,0,1.4))-c.location).to_track_quat('-Z','Y')).to_euler();s.camera=c;bpy.ops.wm.save_as_mainfile(filepath=os.path.join(d,a+'@4.0.0.blend'))
 for lab,ang in [('FRONT',0),('BACK',math.pi),('LEFT',math.pi/2),('RIGHT',-math.pi/2)]:c.location=(math.sin(ang)*12,-math.cos(ang)*12,1.5);c.rotation_euler=((Vector((0,0,1.4))-c.location).to_track_quat('-Z','Y')).to_euler();s.render.filepath=os.path.join(d,lab+'.png');bpy.ops.render.render(write_still=True)
 c.location=(0,-12,1.5);c.rotation_euler=((Vector((0,0,1.4))-c.location).to_track_quat('-Z','Y')).to_euler();s.render.filepath=os.path.join(d,'GAMEPLAY.png');bpy.ops.render.render(write_still=True);c.data.ortho_scale=2.8;s.render.filepath=os.path.join(d,'CLOSE_UP.png');bpy.ops.render.render(write_still=True);black=mat('BLACK',(0,0,0,1));old=[(z,list(z.data.materials)) for z in o];[z.data.materials.clear() or z.data.materials.append(black) for z in o];s.render.filepath=os.path.join(d,'SILHOUETTE.png');bpy.ops.render.render(write_still=True);idmat=mat('ID',(1,0,0,1));[z.data.materials.clear() or z.data.materials.append(idmat) for z in o];s.render.filepath=os.path.join(d,'COMPONENT_ID.png');bpy.ops.render.render(write_still=True);st={'triangles':12*len(o),'vertices':8*len(o),'objects':len(o),'materials':7,'textures':0,'fileSizeBytes':os.path.getsize(os.path.join(d,a+'@4.0.0.blend')),'anonymousGeometryCount':0};json.dump(st,open(os.path.join(d,'BUDGET.json'),'w'),indent=2)
for a,k in [('GG-BLD-AWNING-SHOP-FABRIC-001','awning'),('GG-BLD-WINDOW-SHOP-LARGE-002','window'),('GG-BLD-FASCIA-SHOP-NAVY-001','fascia'),('GG-BLD-DOOR-SHOP-002','door'),('GG-VEG-PLANTER-SHRUB-001','shrub')]:build(a,k)
