import bpy, os, sys, json, math
from mathutils import Vector

args=sys.argv[sys.argv.index('--')+1:]
art, out=args[:2]
os.makedirs(out, exist_ok=True)
bpy.ops.wm.read_factory_settings(use_empty=True)
scene=bpy.context.scene
root=bpy.data.objects.new('GG_ROOT_RESTAURANT_SIMPLE_THE_SAD_TOMATO_001',None);bpy.context.collection.objects.link(root)
root['assetId']='GG-BLD-RESTAURANT-SIMPLE-THE-SAD-TOMATO-001';root['assetVersion']='1.0.0';root['layer']='LAYER_B_RECIPE';root['anonymousGeometry']=False
U=4.4/576; X=lambda p:(p-338)*U; Z=lambda p:(585-p)*U; objects=[]
def plane(name,file,x0,x1,y0,y1,asset,cid,depth,layer):
 me=bpy.data.meshes.new(name+'_MESH');me.from_pydata([(X(x0),depth,Z(y1)),(X(x1),depth,Z(y1)),(X(x1),depth,Z(y0)),(X(x0),depth,Z(y0))],[],[(0,1,2,3)]);me.uv_layers.new()
 for loop,uv in zip(me.uv_layers.active.data,[(0,0),(1,0),(1,1),(0,1)]):loop.uv=uv
 o=bpy.data.objects.new(name,me);bpy.context.collection.objects.link(o);im=bpy.data.images.load(os.path.join(art,file),check_existing=False)
 m=bpy.data.materials.new('UNLIT_'+name);m.use_nodes=True;n=m.node_tree.nodes;n.clear();outn=n.new('ShaderNodeOutputMaterial');e=n.new('ShaderNodeEmission');t=n.new('ShaderNodeTexImage');tr=n.new('ShaderNodeBsdfTransparent');mix=n.new('ShaderNodeMixShader');t.image=im
 m.node_tree.links.new(t.outputs['Color'],e.inputs['Color']);m.node_tree.links.new(t.outputs['Alpha'],mix.inputs[0]);m.node_tree.links.new(tr.outputs[0],mix.inputs[1]);m.node_tree.links.new(e.outputs[0],mix.inputs[2]);m.node_tree.links.new(mix.outputs[0],outn.inputs[0]);m.surface_render_method='DITHERED';me.materials.append(m)
 o['assetId']=asset;o['assetVersion']='1.0.0';o['componentId']=cid;o['layer']=layer;o['runtimeArtifact']=file;o['reused']=layer!='NEW_PRESENTATION';o['anonymousGeometry']=False;objects.append(o);return o
def teal_window_backing():
 me=bpy.data.meshes.new('APPROVED_WINDOW_TEAL_BACKING_MESH');me.from_pydata([(X(106),-.30,Z(496)),(X(350),-.30,Z(496)),(X(350),-.30,Z(307)),(X(106),-.30,Z(307))],[],[(0,1,2,3)])
 o=bpy.data.objects.new('APPROVED_WINDOW_TEAL_BACKING',me);bpy.context.collection.objects.link(o);m=bpy.data.materials.new('GG_MAT_WINDOW_TEAL_APPROVED');m.use_nodes=True;n=m.node_tree.nodes;n.clear();outn=n.new('ShaderNodeOutputMaterial');e=n.new('ShaderNodeEmission');e.inputs['Color'].default_value=(.015,.16,.20,1);m.node_tree.links.new(e.outputs[0],outn.inputs[0]);me.materials.append(m)
 o['assetId']='GG-BLD-WINDOW-SHOP-LARGE-002';o['assetVersion']='1.0.0';o['componentId']='WINDOW_INTERIOR_TEAL_APPROVED';o['layer']='CORE_APPROVED_STRUCTURE';o['runtimeArtifact']='APPROVED_WINDOW_TEAL_INTERIOR';o['reused']=True;o['anonymousGeometry']=False;objects.append(o)
def approved_glass():
 me=bpy.data.meshes.new('APPROVED_WINDOW_GLASS_MESH');me.from_pydata([(X(106),-.33,Z(496)),(X(350),-.33,Z(496)),(X(350),-.33,Z(307)),(X(106),-.33,Z(307))],[],[(0,1,2,3)])
 o=bpy.data.objects.new('APPROVED_WINDOW_GLASS',me);bpy.context.collection.objects.link(o);m=bpy.data.materials.new('GG_MAT_WINDOW_GLASS_TEAL_APPROVED');m.use_nodes=True;n=m.node_tree.nodes;n.clear();outn=n.new('ShaderNodeOutputMaterial');e=n.new('ShaderNodeEmission');e.inputs['Color'].default_value=(.05,.42,.48,1);tr=n.new('ShaderNodeBsdfTransparent');mix=n.new('ShaderNodeMixShader');mix.inputs[0].default_value=.12;m.node_tree.links.new(tr.outputs[0],mix.inputs[1]);m.node_tree.links.new(e.outputs[0],mix.inputs[2]);m.node_tree.links.new(mix.outputs[0],outn.inputs[0]);m.surface_render_method='DITHERED';me.materials.append(m)
 o['assetId']='GG-BLD-WINDOW-SHOP-LARGE-002';o['assetVersion']='1.0.0';o['componentId']='WINDOW_GLASS_APPROVED';o['layer']='CORE_APPROVED_STRUCTURE';o['runtimeArtifact']='APPROVED_WINDOW_GLASS';o['reused']=True;o['anonymousGeometry']=False;objects.append(o)
def shell(name,asset,loc,dims):
 bpy.ops.mesh.primitive_cube_add(size=1,location=loc);o=bpy.context.object;o.name=name;o.dimensions=dims;bpy.ops.object.transform_apply(location=False,rotation=False,scale=True);o['assetId']=asset;o['assetVersion']='1.0.0';o['componentId']=name;o['layer']='CORE_APPROVED_STRUCTURE';o['runtimeArtifact']='APPROVED_COMMERCIAL_SIMPLE_SHELL';o['reused']=True;o['anonymousGeometry']=False;objects.append(o);return o
# These front objects are registered approved artifacts at their locked WINDOW_LEFT / DOOR_RIGHT anchors.
for n,f,a,c,x0,x1,y0,y1,d in [
 ('WALL_LEFT','PRES_WALL_LEFT.png','GG-FAC-WALL-BAY-SIMPLE-001','WALL_LEFT_OF_WINDOW',49,89,256,528,-.20),('WALL_BETWEEN','PRES_WALL_BETWEEN.png','GG-FAC-WALL-PANEL-SIMPLE-001','WALL_BETWEEN_WINDOW_DOOR',367,387,256,528,-.20),('WALL_RIGHT','PRES_WALL_RIGHT.png','GG-FAC-WALL-BAY-SIMPLE-001','WALL_RIGHT_OF_DOOR',582,626,256,528,-.20),('WALL_ABOVE','PRES_WALL_ABOVE.png','GG-FAC-WALL-PANEL-SIMPLE-001','WALL_ABOVE_OPENINGS',49,626,257,275,-.20),('BASE_LEFT','PRES_BASE_LEFT.png','GG-FAC-BASE-PLINTH-SIMPLE-001','BASE_LEFT',17,89,500,586,-.21),('BASE_MIDDLE','PRES_BASE_BETWEEN.png','GG-FAC-BASE-PLINTH-SIMPLE-001','BASE_MIDDLE',89,582,500,586,-.21),('BASE_RIGHT','PRES_BASE_RIGHT.png','GG-FAC-BASE-PLINTH-SIMPLE-001','BASE_RIGHT',582,626,500,586,-.21),('WINDOW_LEFT','PRES_WINDOW.png','GG-BLD-WINDOW-SHOP-LARGE-002','WINDOW_LEFT',89,367,275,506,-.25),('DOOR_RIGHT','PRES_DOOR.png','GG-BLD-DOOR-SHOP-002','DOOR_RIGHT',387,582,256,583,-.26),('FASCIA','PRES_FASCIA_STRUCTURE.png','GG-FAC-FASCIA-BAND-SIMPLE-001','FASCIA',28,672,12,163,-.28)]:plane(n,f,x0,x1,y0,y1,a,c,d,'CORE_APPROVED_STRUCTURE')
teal_window_backing();plane('SAD_TOMATO_DISPLAY','SAD_TOMATO_DISPLAY.png',142,314,325,482,'GG-PRES-WINDOW-DISPLAY-SAD-TOMATO-PASTA-001','SAD_TOMATO_DISPLAY',-.31,'NEW_PRESENTATION');approved_glass()
plane('SAD_TOMATO_AWNING','SAD_TOMATO_AWNING.png',74,627,161,260,'GG-PRES-AWNING-SAD-TOMATO-GREEN-WHITE-STRIPED-001','SAD_TOMATO_AWNING',-.32,'NEW_PRESENTATION');plane('SAD_TOMATO_SIGN','SAD_TOMATO_SIGN.png',158,542,55,113,'GG-PRES-SIGN-THE-SAD-TOMATO-001','SAD_TOMATO_SIGN',-.34,'NEW_PRESENTATION')
# Approved complete-shell artifacts, reused solely for the non-front QA views.
shell('SHELL_LEFT','GG-BLD-WALL-SIDE-COMMERCIAL-SIMPLE-001',(-2.35,1.25,1.85),(.10,2.5,3.7));shell('SHELL_RIGHT','GG-BLD-WALL-SIDE-COMMERCIAL-SIMPLE-001',(2.35,1.25,1.85),(.10,2.5,3.7));shell('SHELL_REAR','GG-BLD-WALL-REAR-COMMERCIAL-SIMPLE-001',(0,2.5,1.85),(4.8,.10,3.7));shell('SHELL_FLOOR','GG-BLD-FLOOR-FOOTPRINT-SIMPLE-001',(0,1.25,.08),(4.8,2.5,.12));shell('SHELL_ROOF_BACK','GG-BLD-ROOF-BACK-SHELL-COMMERCIAL-001',(0,1.25,3.75),(4.8,2.5,.12));shell('SHELL_CORNER_L','GG-BLD-CORNER-COMMERCIAL-SIMPLE-001',(-2.35,2.5,1.85),(.12,.12,3.7));shell('SHELL_CORNER_R','GG-BLD-CORNER-COMMERCIAL-SIMPLE-001',(2.35,2.5,1.85),(.12,.12,3.7))
scene.render.engine='BLENDER_EEVEE';scene.render.resolution_x=760;scene.render.resolution_y=670;scene.render.resolution_percentage=100;scene.render.image_settings.file_format='PNG';scene.view_settings.view_transform='Standard';scene.view_settings.look='None';scene.world=bpy.data.worlds.new('World');scene.world.color=(.82,.82,.82);bpy.ops.object.light_add(type='AREA',location=(0,-4,4));bpy.context.object.data.energy=900;bpy.context.object.data.size=8;bpy.ops.object.camera_add(location=(0,-12,2.2));cam=bpy.context.object;cam.data.type='ORTHO';cam.data.ortho_scale=4.9;scene.camera=cam;target=Vector((0,0,2.2))
def render(n,a=0,e=2.2):
 r=math.radians(a);cam.location=(12*math.sin(r),-12*math.cos(r),e);cam.rotation_euler=((target-cam.location).to_track_quat('-Z','Y')).to_euler();scene.render.filepath=os.path.join(out,n);bpy.ops.render.render(write_still=True)
for label,a,e in [('FRONT',0,2.2),('15_LEFT',15,2.3),('30_LEFT',30,2.4),('15_RIGHT',-15,2.3),('30_RIGHT',-30,2.4),('LEFT',90,2.4),('RIGHT',-90,2.4),('BACK',180,2.4),('TOP_OBLIQUE',25,7)]:render('SAD_TOMATO_V1_'+label+'.png',a,e)
scene.render.engine='BLENDER_WORKBENCH';render('SAD_TOMATO_V1_COMPONENT_ID.png');[setattr(o,'show_wire',True) for o in objects if hasattr(o.data,'polygons')];render('SAD_TOMATO_V1_WIREFRAME.png')
result={'status':'PASS','executionMode':'REAL_BLENDER_WORKER_EXECUTION','blenderVersion':bpy.app.version_string,'assetId':'GG-BLD-RESTAURANT-SIMPLE-THE-SAD-TOMATO-001@1.0.0','baseFacade':'GG-BLD-FACADE-SIMPLE-SHOP-MIRRORED-001@1.0.0','layout':'WINDOW_LEFT_DOOR_RIGHT','newStructuralGeometryTriangles':0,'presentationTriangles':6,'anonymousGeometry':0,'buildIterations':1,'sourceIds':{o.name:o['assetId'] for o in objects},'depthOrder':['AWNING','WINDOW_CASING','APPROVED_WINDOW_GLASS','SAD_TOMATO_DISPLAY','WINDOW_INTERIOR']}
json.dump(result,open(os.path.join(out,'SAD_TOMATO_V1_RESULT.json'),'w'),indent=2);bpy.ops.wm.save_as_mainfile(filepath=os.path.join(out,'GG-BLD-RESTAURANT-SIMPLE-THE-SAD-TOMATO-001_V1_CANDIDATE.blend'))
