import bpy,sys,os,json
from mathutils import Vector
src,out=sys.argv[sys.argv.index('--')+1:];os.makedirs(out,exist_ok=True);bpy.ops.wm.read_factory_settings(use_empty=True)
W,H=300,350;img=bpy.data.images.load(src,check_existing=False);img.colorspace_settings.name='sRGB'
bpy.ops.mesh.primitive_plane_add(size=2,location=(0,0,0));p=bpy.context.object;p.name='DOOR_DIRECT_REFERENCE_PLANE';p.dimensions=(W/H,1,1);bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)
m=bpy.data.materials.new('DOOR_DIRECT_REFERENCE_EMISSION');m.use_nodes=True;n=m.node_tree.nodes;n.clear();outn=n.new('ShaderNodeOutputMaterial');em=n.new('ShaderNodeEmission');tex=n.new('ShaderNodeTexImage');tex.image=img;tex.interpolation='Closest';m.node_tree.links.new(tex.outputs['Color'],em.inputs['Color']);m.node_tree.links.new(em.outputs['Emission'],outn.inputs['Surface']);em.inputs['Strength'].default_value=1.0;p.data.materials.append(m)
bpy.ops.object.camera_add(location=(0,0,1));c=bpy.context.object;c.name='DOOR_DIRECT_REFERENCE_ORTHO_CAMERA';c.data.type='ORTHO';c.data.ortho_scale=1.0;c.rotation_euler=(0,0,0)
s=bpy.context.scene;s.camera=c;s.render.resolution_x=W;s.render.resolution_y=H;s.render.resolution_percentage=100;s.render.image_settings.file_format='PNG';s.render.image_settings.color_mode='RGBA';s.render.film_transparent=False;s.render.engine='BLENDER_WORKBENCH';s.display.shading.light='FLAT';s.display.shading.color_type='TEXTURE';s.view_settings.view_transform='Standard';s.view_settings.look='None';s.view_settings.exposure=0;s.view_settings.gamma=1;s.render.filepath=os.path.join(out,'DOOR_DIRECT_REFERENCE_RENDER.png');bpy.ops.render.render(write_still=True);bpy.ops.wm.save_as_mainfile(filepath=os.path.join(out,'DOOR_DIRECT_REFERENCE.blend'))
json.dump({'sourceDimensions':[W,H],'renderDimensions':[W,H],'cameraType':'ORTHO','orthoScale':1.0,'uvCoverage':'FULL_ONCE','material':'EMISSION_UNLIT','imageColorSpace':'sRGB','viewTransform':'Standard','look':'None','exposure':0,'gamma':1,'outputColorSpace':'sRGB'},open(os.path.join(out,'DOOR_DIRECT_REFERENCE_SETTINGS.json'),'w'),indent=2)
