import bpy,os,sys,math,json
from mathutils import Vector
args=sys.argv[sys.argv.index('--')+1:];out,art=args[:2];os.makedirs(out,exist_ok=True);bpy.ops.wm.read_factory_settings(use_empty=True)
U=4.4/576; X=lambda px:(px-338)*U; Z=lambda px:(585-px)*U
def mat(n,c):
 m=bpy.data.materials.new(n);m.diffuse_color=(*c,1);return m
WALL=mat('MAT_WALL_WARM_TERRACOTTA',(.29,.12,.06));CREAM=mat('MAT_TRIM_WARM_CREAM',(.75,.60,.39));NAVY=mat('MAT_FASCIA_NAVY',(.025,.04,.13));PLUM=mat('MAT_AWNING_PLUM',(.36,.07,.28));DARK=mat('MAT_DARK_REVEAL',(.02,.01,.008));mats=[WALL,CREAM,NAVY,PLUM,DARK]
root=bpy.data.objects.new('GG_ROOT_FACADE_COMMERCIAL_SIMPLE_001',None);bpy.context.collection.objects.link(root);objs=[]
def box(name,x0,x1,z0,z1,y,d,mid,material,aid):
 bpy.ops.mesh.primitive_cube_add(size=1,location=((x0+x1)/2,y,(z0+z1)/2));o=bpy.context.object;o.name=name;o.dimensions=(x1-x0,d,z1-z0);bpy.ops.object.transform_apply(location=False,rotation=False,scale=True);o.data.materials.append(material);o.parent=root;o['assetId']=aid;o['componentId']=mid;o['layer']='LAYER_A_MODULE';o['anonymousGeometry']=False;objs.append(o);return o
# Reusable wall bays deliberately stop at approved opening anchors: no copied door/window casing.
for n,x0,x1,z0,z1,aid in [('WALL_LEFT_OF_DOOR',49,89,257,500,'GG-FAC-WALL-BAY-SIMPLE-001'),('WALL_BETWEEN_DOOR_WINDOW',284,304,257,500,'GG-FAC-WALL-PANEL-SIMPLE-001'),('WALL_RIGHT_OF_WINDOW',582,626,257,500,'GG-FAC-WALL-BAY-SIMPLE-001'),('WALL_ABOVE_OPENINGS',49,626,257,275,'GG-FAC-WALL-PANEL-SIMPLE-001')]:box(n,X(x0),X(x1),Z(z1),Z(z0),.06,.06,n,WALL,aid)
for n,x0,x1,z0,z1,aid in [('BASE_PLINTH',17,626,500,585,'GG-FAC-BASE-PLINTH-SIMPLE-001'),('BASE_BAND',49,626,500,525,'GG-FAC-BASE-BAND-SIMPLE-001'),('LEFT_PILASTER',49,89,256,500,'GG-FAC-PILASTER-VERTICAL-SIMPLE-001'),('RIGHT_PILASTER',582,626,256,500,'GG-FAC-PILASTER-VERTICAL-SIMPLE-001'),('FASCIA_BAND',28,672,12,158,'GG-FAC-FASCIA-BAND-SIMPLE-001'),('TOP_CAP',28,672,12,35,'GG-FAC-HEAD-CORNICE-SIMPLE-001'),('AWNING_RAIL',74,627,155,168,'GG-FAC-AWNING-RAIL-SIMPLE-001')]:box(n,X(x0),X(x1),Z(z1),Z(z0),.08,.08,n,CREAM if 'FASCIA' not in n and 'TOP' not in n else NAVY,aid)
# Separate swappable awning/sign/planter placeholders. Art planes below provide their front authority.
box('AWNING_STRUCTURE',X(74),X(627),Z(260),Z(161),-.02,.22,'AWNING',PLUM,'GG-BLD-AWNING-COMMERCIAL-001')
box('SIGN_FASCIA_STRUCTURE',X(158),X(542),Z(113),Z(55),-.025,.06,'SIGN',NAVY,'GG-BLD-SIGN-FASCIA-COMMERCIAL-001')
# Attached approved modules are presentation planes with their permanent identities. No façade-owned trim overlaps their measured bounds.
def image_plane(name,file,x0,x1,y0,y1,asset,component,y=-.12):
 me=bpy.data.meshes.new(name+'_MESH');me.from_pydata([(X(x0),y,Z(y1)),(X(x1),y,Z(y1)),(X(x1),y,Z(y0)),(X(x0),y,Z(y0))],[],[(0,1,2,3)]);me.uv_layers.new();uv=me.uv_layers.active.data;coords=[(0,0),(1,0),(1,1),(0,1)];[setattr(uv[i],'uv',coords[i]) for i in range(4)];o=bpy.data.objects.new(name,me);bpy.context.collection.objects.link(o);o.parent=root;o['assetId']=asset;o['componentId']=component;o['layer']='LAYER_A_MODULE';o['anonymousGeometry']=False;im=bpy.data.images.load(os.path.join(art,file),check_existing=False);m=bpy.data.materials.new('UNLIT_'+name);m.use_nodes=True;nd=m.node_tree.nodes;nd.clear();outn=nd.new('ShaderNodeOutputMaterial');em=nd.new('ShaderNodeEmission');tx=nd.new('ShaderNodeTexImage');tr=nd.new('ShaderNodeBsdfTransparent');mix=nd.new('ShaderNodeMixShader');tx.image=im;m.node_tree.links.new(tx.outputs['Color'],em.inputs['Color']);m.node_tree.links.new(tx.outputs['Alpha'],mix.inputs[0]);m.node_tree.links.new(tr.outputs[0],mix.inputs[1]);m.node_tree.links.new(em.outputs[0],mix.inputs[2]);m.node_tree.links.new(mix.outputs[0],outn.inputs[0]);m.surface_render_method='DITHERED';me.materials.append(m);objs.append(o)
image_plane('APPROVED_DOOR_01','APPROVED_DOOR_FRONT.png',89,284,256,583,'GG-BLD-DOOR-SHOP-002','ANCHOR_DOOR_01')
image_plane('APPROVED_WINDOW_01','APPROVED_WINDOW_FRONT.png',304,582,275,506,'GG-BLD-WINDOW-SHOP-LARGE-002','ANCHOR_WINDOW_01')
for n,f,x0,x1,y0,y1,aid in [('WALL_LEFT_ART','FACADE_WALL_LEFT_ART.png',49,89,256,528,'GG-FAC-WALL-BAY-SIMPLE-001'),('WALL_BETWEEN_ART','FACADE_WALL_BETWEEN_ART.png',284,304,256,528,'GG-FAC-WALL-PANEL-SIMPLE-001'),('WALL_RIGHT_ART','FACADE_WALL_RIGHT_ART.png',582,626,256,528,'GG-FAC-WALL-BAY-SIMPLE-001'),('WALL_ABOVE_ART','FACADE_WALL_ABOVE_ART.png',49,626,257,275,'GG-FAC-WALL-PANEL-SIMPLE-001'),('BASE_LEFT_ART','FACADE_BASE_LEFT_ART.png',17,89,500,586,'GG-FAC-BASE-PLINTH-SIMPLE-001'),('BASE_BETWEEN_ART','FACADE_BASE_BETWEEN_ART.png',284,582,500,586,'GG-FAC-BASE-PLINTH-SIMPLE-001'),('BASE_RIGHT_ART','FACADE_BASE_RIGHT_ART.png',582,626,500,586,'GG-FAC-BASE-PLINTH-SIMPLE-001')]:image_plane(n,f,x0,x1,y0,y1,aid,n,-.13)
for n,f,x0,x1,y0,y1,aid in [('FASCIA_ART','FACADE_FASCIA_ART.png',28,672,12,163,'GG-FAC-FASCIA-BAND-SIMPLE-001'),('AWNING_ART','FACADE_AWNING_ART.png',74,627,161,260,'GG-BLD-AWNING-COMMERCIAL-001')]:image_plane(n,f,x0,x1,y0,y1,aid,n,-.14)
# camera / renders
s=bpy.context.scene;s.render.engine='BLENDER_EEVEE';s.render.resolution_x=760;s.render.resolution_y=670;s.render.resolution_percentage=100;s.render.image_settings.file_format='PNG';s.view_settings.view_transform='Standard';s.view_settings.look='None';s.world=bpy.data.worlds.new('FacadeWorld');s.world.color=(.82,.82,.82);bpy.ops.object.light_add(type='AREA',location=(0,-4,4));bpy.context.object.data.energy=900;bpy.context.object.data.shape='RECTANGLE';bpy.context.object.data.size=8;bpy.context.object.rotation_euler=(math.radians(35),0,0);bpy.ops.object.camera_add(location=(0,-12,2.2));cam=bpy.context.object;cam.data.type='ORTHO';cam.data.ortho_scale=4.9;s.camera=cam;target=Vector((0,0,2.2));cam.rotation_euler=((target-cam.location).to_track_quat('-Z','Y')).to_euler()
def render(n):s.render.filepath=os.path.join(out,n);bpy.ops.render.render(write_still=True)
render('SIMPLE_SHOP_FACADE_V1_FRONT.png')
for deg,label in [(15,'15_LEFT'),(30,'30_LEFT'),(-15,'15_RIGHT'),(-30,'30_RIGHT'),(180,'BACK')]:
 a=math.radians(deg);cam.location=(12*math.sin(a),-12*math.cos(a),2.2);cam.rotation_euler=((target-cam.location).to_track_quat('-Z','Y')).to_euler();render('SIMPLE_SHOP_FACADE_V1_'+label+'.png')
# component IDs
for o in objs:o.hide_render=False
s.render.engine='BLENDER_WORKBENCH';render('SIMPLE_SHOP_FACADE_V1_COMPONENT_ID.png');[setattr(o,'show_wire',True) for o in objs];render('SIMPLE_SHOP_FACADE_V1_WIREFRAME.png')
tri=sum(sum(max(0,len(p.vertices)-2) for p in o.data.polygons) for o in objs);budget={'triangles':tri,'vertices':sum(len(o.data.vertices) for o in objs),'materials':len(mats),'facadeSpecificArtBytes':sum(os.path.getsize(os.path.join(art,f)) for f in ['FACADE_FASCIA_ART.png','FACADE_AWNING_ART.png']),'anonymousGeometry':0,'status':'PASS'}
json.dump({'status':'PASS','blenderVersion':bpy.app.version_string,'budget':budget,'componentIds':[o['componentId'] for o in objs],'anonymousGeometry':0},open(os.path.join(out,'SIMPLE_SHOP_FACADE_V1_RESULT.json'),'w'),indent=2);bpy.ops.wm.save_as_mainfile(filepath=os.path.join(out,'GG-BLD-FACADE-SIMPLE-SHOP-001_V1.blend'))
