import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createWorkerJob, canonicalJson, fileChecksum, WorkerContractError } from "../asset-factory/golden-reference/external-blender-worker-contract.mjs";
import { createTransportPackage, dispatchLocalFolder, receiveWorkerResult } from "../asset-factory/golden-reference/external-blender-worker-transport.mjs";
import { validateWorkerPackage, generateWorkerBlenderScript, processWorkerPackage, WORKER_VERSION } from "../asset-factory/blender-worker/worker-package-consumer.mjs";
import { encodePng } from "../asset-factory/golden-reference/golden-reference-raster-analysis.mjs";

const root = fs.mkdtempSync(path.join(os.tmpdir(), "growgo-worker-consumer-"));
const ref = path.join(root, "reference.png"); fs.writeFileSync(ref, encodePng(32, 32, Buffer.alloc(32 * 32 * 4, 255)));
function makeInput(name = `job-${Date.now()}`) { const j = createWorkerJob({ jobId: `JOB-${name}`, backend: "EXTERNAL_BLENDER", assetId: "ASSET-001", assetVersion: "1.0.0", recipeId: "RECIPE-001", recipeVersion: "1.0.0", blenderBuildId: "BLENDER-WORKER-BUILD-001", goldenReference: { referenceId: "REF-001", referenceVersion: "1.0.0", checksum: fileChecksum(ref) }, componentMappings: [], modules: [{ componentId: "BODY", assetId: "MODULE-001", assetVersion: "1.0.0", moduleId: "MODULE-001", moduleVersion: "1.0.0", moduleFamily: "BUILDING", recipeId: "RECIPE-001", recipeVersion: "1.0.0" }], operations: [{ componentId: "BODY", objectId: "BODY-OBJ", operation: "SCALE_X", value: 1.1, moduleId: "MODULE-001", moduleVersion: "1.0.0" }], protectedComponents: ["BODY"], protectedObjectIds: ["BODY-OBJ"], budgetProfile: { profileId: "LIGHT", hardTriangleCeiling: 1000, hardVertexCeiling: 1000, hardMaterialCeiling: 2 }, cameraContract: { id: "CAM-001", projection: "ORTHOGRAPHIC_LOCKED", resolution: "32x32" }, renderContract: { format: "PNG", colorMode: "RGBA", width: 32, height: 32 }, exportContract: { blendOutput: "fixture.blend" }, checksums: { sourceBuild: "BUILD-001", goldenReference: fileChecksum(ref), recipe: "RECIPE-CHECKSUM" } }); const jobFile = path.join(root, `${name}-job.json`); fs.writeFileSync(jobFile, `${canonicalJson(j)}\n`); const pkgRoot = path.join(root, `${name}-package`); const pkg = createTransportPackage({ job: j, artifacts: { jobPath: jobFile, items: [] }, transportJobId: `TRANSPORT-${name}`, sourceBuildId: "BUILD-001", createdAt: "2026-01-01T00:00:00.000Z", packageRoot: pkgRoot }); return { j, pkg, jobFile }; }
function expectCode(fn, code) { assert.throws(fn, e => e instanceof WorkerContractError && e.code === code); }

test("valid package ingestion", () => { const i = makeInput("valid"); const v = validateWorkerPackage(i.pkg.root, { now: new Date("2026-01-01T00:00:01Z") }); assert.equal(v.status, "PACKAGE_VALIDATED"); assert.equal(v.job.jobId, i.j.jobId); });
test("invalid package rejection", () => { const i = makeInput("invalid"); fs.writeFileSync(path.join(i.pkg.root, "JOB_ENVELOPE.json"), "{}"); expectCode(() => validateWorkerPackage(i.pkg.root), "WORKER_PACKAGE_INVALID"); });
test("package checksum rejection", () => { const i = makeInput("checksum"); fs.appendFileSync(path.join(i.pkg.root, "BLENDER_WORKER_JOB.json"), "tamper"); expectCode(() => validateWorkerPackage(i.pkg.root), "WORKER_PACKAGE_INVALID"); });
test("expiry rejection", () => { const i = makeInput("expiry"); const envelope = JSON.parse(fs.readFileSync(path.join(i.pkg.root, "JOB_ENVELOPE.json"))); envelope.expiresAt = "2020-01-01T00:00:00Z"; fs.writeFileSync(path.join(i.pkg.root, "JOB_ENVELOPE.json"), JSON.stringify(envelope)); expectCode(() => validateWorkerPackage(i.pkg.root, { now: new Date("2026-01-01T00:00:00Z") }), "WORKER_PACKAGE_EXPIRED"); });
test("operation allowlist", () => { const i = makeInput("allow"); assert.doesNotThrow(() => generateWorkerBlenderScript(i.j)); });
test("arbitrary shell rejection", () => { const i = makeInput("shell"); i.j.shell = "rm -rf"; fs.writeFileSync(path.join(i.pkg.root, "BLENDER_WORKER_JOB.json"), JSON.stringify(i.j)); expectCode(() => validateWorkerPackage(i.pkg.root), "WORKER_ARTIFACT_CHECKSUM_FAIL"); });
test("arbitrary Python rejection", () => { const i = makeInput("python"); const j = { ...i.j, python: "import bpy" }; fs.writeFileSync(path.join(i.pkg.root, "BLENDER_WORKER_JOB.json"), JSON.stringify(j)); expectCode(() => validateWorkerPackage(i.pkg.root), "WORKER_ARTIFACT_CHECKSUM_FAIL"); });
test("deterministic Blender script generation", () => { const i = makeInput("script"); assert.equal(generateWorkerBlenderScript(i.j), generateWorkerBlenderScript(structuredClone(i.j))); assert.match(generateWorkerBlenderScript(i.j), new RegExp(WORKER_VERSION)); });
test("worker-local runtime certification is required for real mode", () => { const i = makeInput("runtime"); expectCode(() => processWorkerPackage({ packageRoot: i.pkg.root, outputRoot: path.join(root, "runtime-out"), runtime: { mode: "REAL" } }), "WORKER_RUNTIME_NOT_CERTIFIED"); });
test("mock runtime executes only as contract proof", () => { const i = makeInput("mock"); const out = processWorkerPackage({ packageRoot: i.pkg.root, outputRoot: path.join(root, "mock-out"), runtime: { mode: "MOCK" } }); assert.equal(out.mode, "MOCK"); assert.equal(out.status, "COMPLETE"); });
test("source build is preserved and versioned output is created", () => { const i = makeInput("source"); const before = fileChecksum(i.jobFile); const out = processWorkerPackage({ packageRoot: i.pkg.root, outputRoot: path.join(root, "source-out"), runtime: { mode: "MOCK" } }); assert.equal(fileChecksum(i.jobFile), before); assert.notEqual(out.result.outputBuildId, out.result.sourceBuildId); assert.ok(fs.existsSync(path.join(out.resultRoot, "artifacts", `${out.result.outputBuildId}.blend`))); });
test("module identity survives worker result", () => { const i = makeInput("modules"); const out = processWorkerPackage({ packageRoot: i.pkg.root, outputRoot: path.join(root, "modules-out"), runtime: { mode: "MOCK" } }); assert.equal(out.result.modules[0].moduleId, "MODULE-001"); assert.equal(out.result.modules[0].recipeId, "RECIPE-001"); });
test("protected component verification is recorded", () => { const i = makeInput("protected"); const out = processWorkerPackage({ packageRoot: i.pkg.root, outputRoot: path.join(root, "protected-out"), runtime: { mode: "MOCK" } }); assert.equal(out.result.protectedObjectValidation.allStable, true); });
test("camera contract is preserved", () => { const i = makeInput("camera"); const out = processWorkerPackage({ packageRoot: i.pkg.root, outputRoot: path.join(root, "camera-out"), runtime: { mode: "MOCK" } }); assert.deepEqual(out.result.cameraValidation, i.j.cameraContract); });
test("render metadata and stats are produced", () => { const i = makeInput("render"); const out = processWorkerPackage({ packageRoot: i.pkg.root, outputRoot: path.join(root, "render-out"), runtime: { mode: "MOCK" } }); assert.equal(out.result.render.colorMode, "RGBA"); assert.equal(out.result.render.format, "PNG"); assert.ok(out.result.blenderStats.objectCount >= 1); });
test("GLB contract remains explicit and does not fabricate undeclared exports", () => { const i = makeInput("glb"); const out = processWorkerPackage({ packageRoot: i.pkg.root, outputRoot: path.join(root, "glb-out"), runtime: { mode: "MOCK" } }); assert.deepEqual(out.result.blenderStats.glbFileSizes, {}); assert.equal(out.result.exportArtifacts.length, 1); });
test("result JSON and return manifest are generated", () => { const i = makeInput("manifest"); const out = processWorkerPackage({ packageRoot: i.pkg.root, outputRoot: path.join(root, "manifest-out"), runtime: { mode: "MOCK" } }); assert.ok(fs.existsSync(path.join(out.resultRoot, "BLENDER_WORKER_RESULT.json"))); assert.equal(out.manifest.artifactCount, 3); });
test("deterministic result packaging", () => { const a = makeInput("det-same"); const b = makeInput("det-same"); const oa = processWorkerPackage({ packageRoot: a.pkg.root, outputRoot: path.join(root, "det-out-a"), runtime: { mode: "MOCK" } }); const ob = processWorkerPackage({ packageRoot: b.pkg.root, outputRoot: path.join(root, "det-out-b"), runtime: { mode: "MOCK" } }); assert.equal(canonicalJson(oa.manifest), canonicalJson(ob.manifest)); assert.equal(canonicalJson(oa.result), canonicalJson(ob.result)); });
test("retry safety and idempotent reprocessing detect completed output", () => { const i = makeInput("retry"); const out = processWorkerPackage({ packageRoot: i.pkg.root, outputRoot: path.join(root, "retry-out"), runtime: { mode: "MOCK" } }); const again = processWorkerPackage({ packageRoot: i.pkg.root, outputRoot: out.resultRoot, runtime: { mode: "MOCK" } }); assert.equal(again.result.outputBuildId, out.result.outputBuildId); });
test("worker failure does not claim completion", () => { const i = makeInput("failure"); expectCode(() => processWorkerPackage({ packageRoot: i.pkg.root, outputRoot: path.join(root, "failure-out"), runtime: { mode: "REAL" } }), "WORKER_RUNTIME_NOT_CERTIFIED"); });
test("controller receipt accepts valid worker output and raster handoff", () => { const i = makeInput("controller"); const dispatched = dispatchLocalFolder(i.pkg, path.join(root, "controller-dispatch"), { dispatchedAt: "2026-01-01T00:00:02Z" }); const out = processWorkerPackage({ packageRoot: dispatched.root, outputRoot: path.join(root, "controller-result"), runtime: { mode: "MOCK" } }); const receipt = receiveWorkerResult({ transportPackage: dispatched, resultRoot: out.resultRoot, referencePath: ref }); assert.equal(receipt.status, "ACCEPTED"); assert.equal(receipt.raster.analysis.ok, true); });
