import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { decodePng, exactPixelComparison } from '../asset-factory/golden-reference/golden-reference-raster-analysis.mjs';
const root=path.resolve(import.meta.dirname,'..');
const modular=path.join(root,'asset-factory/modular');
const output=path.join(root,'test-output/commercial-simple-window-runtime-decomposition-v1');
const read=name=>JSON.parse(fs.readFileSync(path.join(modular,name),'utf8'));
const runtime=read('COMMERCIAL_SIMPLE_WINDOW_RUNTIME_DECOMPOSITION_V1.json');
const contamination=read('COMMERCIAL_SIMPLE_WINDOW_LAYER_CONTAMINATION_AUDIT_V1.json');
const sourceAudit=read('COMMERCIAL_SIMPLE_WINDOW_SOURCE_LAYER_EXTRACTION_AUDIT_V1.json');
assert.equal(runtime.status,'VALID');
assert.equal(runtime.states.GROW_GOODS.pass,true);
assert.equal(runtime.states.EMPTY.pass,true);
assert.equal(runtime.states.PIZZA.pass,true);
assert.equal(runtime.states.SAD_TOMATO.pass,true);
assert.equal(contamination.checks.INTERIOR_BACKING.growGoodsDisplayPixels,0);
assert.equal(contamination.checks.GLASS_PRESENTATION.displayPixels,0);
assert.equal(contamination.checks.CASING_STRUCTURE.displayPixels,0);
assert.equal(contamination.fallbackCard.teal,false);
assert.equal(contamination.fallbackCard.white,false);
assert.equal(runtime.permanentWindowIdPreserved,true);
assert.equal(runtime.approvedAuthorityChanged,false);
assert.equal(runtime.sadTomatoRebuilt,false);
assert.equal(sourceAudit.calibratedTransforms.guideDrift,0);
for(const file of ['COMMERCIAL_SIMPLE_WINDOW_GROW_GOODS_DISPLAY_MASK_V1.png','COMMERCIAL_SIMPLE_WINDOW_INTERIOR_BACKING_V1.png','COMMERCIAL_SIMPLE_WINDOW_DECOMPOSED_GROW_GOODS_V2.png','COMMERCIAL_SIMPLE_WINDOW_EMPTY_DISPLAY_V1.png','COMMERCIAL_SIMPLE_WINDOW_PIZZA_DISPLAY_V1.png','COMMERCIAL_SIMPLE_WINDOW_SAD_TOMATO_DISPLAY_V1.png']) assert.equal(fs.existsSync(path.join(output,file)),true,file);
const same=exactPixelComparison(decodePng(path.join(root,'test-output/simple-shop-facade-v1/APPROVED_WINDOW_FRONT.png')),decodePng(path.join(output,'COMMERCIAL_SIMPLE_WINDOW_DECOMPOSED_GROW_GOODS_V2.png')));
assert.equal(same.exact,true);
console.log('commercial simple window runtime decomposition: PASS (20 assertions)');
