import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createHash } from "node:crypto";
import { createWorkerJob, fileChecksum, canonicalJson, WorkerContractError } from "../asset-factory/golden-reference/external-blender-worker-contract.mjs";
import { encodePng } from "../asset-factory/golden-reference/golden-reference-raster-analysis.mjs";
import { createArtifactManifest, createTransportPackage, dispatchLocalFolder, receiveWorkerResult } from "../asset-factory/golden-reference/external-blender-worker-transport.mjs";

const root = fs.mkdtempSync(path.join(os.tmpdir(), "growgo-transport-"));
const ref = path.join(root, "GOLDEN_REFERENCE.png"); const render = path.join(root, "BLENDER_RENDER.png");
const pixels = Buffer.alloc(32 * 32 * 4, 255); fs.writeFileSync(ref, encodePng(32, 32, pixels)); fs.writeFileSync(render, encodePng(32, 32, pixels));
const referenceChecksum = fileChecksum(ref);
let resultCounter = 0;
function job() { return createWorkerJob({ jobId: "WORKER-JOB-001", backend: "EXTERNAL_BLENDER", assetId: "ASSET-001", assetVersion: "1.0.0", recipeId: "RECIPE-001", recipeVersion: "1.0.0", blenderBuildId: "BUILD-001", goldenReference: { referenceId: "REF-001", referenceVersion: "1.0.0", checksum: referenceChecksum }, componentMappings: [], modules: [{ componentId: "BODY", assetId: "MODULE-001", assetVersion: "1.0.0", moduleId: "MODULE-001", moduleVersion: "1.0.0", moduleFamily: "BUILDING" }], operations: [{ componentId: "BODY", objectId: "BODY-OBJ", operation: "SCALE_X", value: 1.1, moduleId: "MODULE-001", moduleVersion: "1.0.0" }], protectedComponents: ["BODY"], budgetProfile: { profileId: "LIGHT", hardTriangleCeiling: 1000, hardVertexCeiling: 1000, hardMaterialCeiling: 2 }, cameraContract: { id: "CAM-001", projection: "ORTHOGRAPHIC_LOCKED", resolution: "32x32" }, renderContract: { format: "PNG", colorMode: "RGBA", width: 32, height: 32 }, exportContract: { blendOutput: "fixture.blend" }, checksums: { sourceBuild: "BUILD-001", goldenReference: referenceChecksum, recipe: "RECIPE-CHECKSUM" } }); }
function makePackage(overrides = {}) { const j = job(); const jobPath = path.join(root, "job.json"); fs.writeFileSync(jobPath, JSON.stringify(j)); const packageRoot = path.join(root, "package", overrides.suffix ?? "one"); return { j, jobPath, packageRoot, pkg: createTransportPackage({ job: j, artifacts: { jobPath, items: [] }, transportJobId: overrides.transportJobId ?? "TRANSPORT-001", sourceBuildId: "BUILD-001", createdAt: "2026-01-01T00:00:00.000Z", packageRoot }) }; }
function resultPackage(pkg, overrides = {}) { const resultRoot = path.join(root, "result", overrides.suffix ?? `result-${++resultCounter}`); fs.mkdirSync(path.join(resultRoot, "artifacts"), { recursive: true }); const result = { jobId: overrides.jobId ?? pkg.envelope.workerJobId, status: "COMPLETED", assetId: overrides.assetId ?? pkg.envelope.assetId, assetVersion: "1.0.0", recipeId: overrides.recipeId ?? pkg.envelope.recipeId, recipeVersion: "1.0.0", blenderVersion: "fixture", executableIdentity: { buildId: "BUILD-001", architecture: "x86_64" }, sourceChecksum: "BUILD-001", goldenReference: { referenceId: "REF-001", referenceVersion: "1.0.0", checksum: referenceChecksum }, modules: [{ componentId: "BODY", assetId: "MODULE-001", assetVersion: "1.0.0", moduleId: "MODULE-001", moduleVersion: "1.0.0", moduleFamily: "BUILDING", recipeId: "RECIPE-001", recipeVersion: "1.0.0" }], protectedObjectValidation: { allStable: true }, budget: { triangles: 10, vertices: 10, materials: 1, objectCount: 1 }, cameraValidation: { id: "CAM-001", projection: "ORTHOGRAPHIC_LOCKED", resolution: "32x32" }, render: { path: render, checksum: fileChecksum(render), format: "PNG", colorMode: "RGBA" }, iteration: 1, oneIterationStop: true };
  fs.writeFileSync(path.join(resultRoot, "BLENDER_WORKER_RESULT.json"), JSON.stringify(result)); fs.copyFileSync(render, path.join(resultRoot, "artifacts", "BLENDER_RENDER.png")); const entries = [{ logicalId: "BLENDER_WORKER_RESULT", filename: "BLENDER_WORKER_RESULT.json", checksum: fileChecksum(path.join(resultRoot, "BLENDER_WORKER_RESULT.json")), byteSize: fs.statSync(path.join(resultRoot, "BLENDER_WORKER_RESULT.json")).size, required: true, artifactType: "JSON" }, { logicalId: "BLENDER_RENDER", filename: "BLENDER_RENDER.png", checksum: fileChecksum(path.join(resultRoot, "artifacts", "BLENDER_RENDER.png")), byteSize: fs.statSync(path.join(resultRoot, "artifacts", "BLENDER_RENDER.png")).size, required: true, artifactType: "PNG_RGBA" }]; fs.writeFileSync(path.join(resultRoot, "ARTIFACT_MANIFEST.json"), JSON.stringify({ transportVersion: "GG-BLENDER-WORKER-TRANSPORT-1.0.0", artifacts: entries, manifestChecksum: createHash("sha256").update(canonicalJson(entries.sort((a,b)=>a.logicalId.localeCompare(b.logicalId)))).digest("hex") })); return { resultRoot, result }; }
function expectCode(fn, code) { assert.throws(fn, e => e instanceof WorkerContractError && e.code === code); }
function refreshResultManifest(r) { const file = path.join(r.resultRoot, "BLENDER_WORKER_RESULT.json"); const manifestFile = path.join(r.resultRoot, "ARTIFACT_MANIFEST.json"); const m = JSON.parse(fs.readFileSync(manifestFile, "utf8")); const entry = m.artifacts.find(x => x.logicalId === "BLENDER_WORKER_RESULT"); entry.checksum = fileChecksum(file); entry.byteSize = fs.statSync(file).size; m.manifestChecksum = createHash("sha256").update(canonicalJson(m.artifacts.sort((a,b)=>a.logicalId.localeCompare(b.logicalId)))).digest("hex"); fs.writeFileSync(manifestFile, JSON.stringify(m)); }

test("deterministic job envelope", () => { const a = makePackage({ suffix: "a", transportJobId: "T-A" }).pkg; const b = makePackage({ suffix: "b", transportJobId: "T-A" }).pkg; assert.deepEqual(a.envelope, b.envelope); });
test("deterministic artifact manifest", () => { const a = makePackage({ suffix: "c" }).pkg; const b = makePackage({ suffix: "d" }).pkg; assert.deepEqual(a.manifest, b.manifest); });
test("deterministic package checksum", () => { assert.equal(makePackage({ suffix: "e" }).pkg.packageChecksum, makePackage({ suffix: "f" }).pkg.packageChecksum); });
test("local-folder dispatch", () => { const p = makePackage({ suffix: "g" }).pkg; const d = dispatchLocalFolder(p, path.join(root, "dispatch"), { dispatchedAt: "2026-01-01T00:00:01.000Z" }); assert.equal(d.status, "DISPATCHED"); assert.ok(fs.existsSync(path.join(d.root, "DISPATCH_RECEIPT.json"))); });
test("dispatch receipt records package and artifact counts", () => { const p = dispatchLocalFolder(makePackage({ suffix: "h" }).pkg, path.join(root, "dispatch2"), { dispatchedAt: "2026-01-01T00:00:01.000Z" }); assert.equal(p.dispatchReceipt.packageChecksum, p.packageChecksum); assert.equal(p.dispatchReceipt.artifactCount, 1); });
test("valid result receipt", () => { const p = dispatchLocalFolder(makePackage({ suffix: "i" }).pkg, path.join(root, "dispatch3")); const r = resultPackage(p); const receipt = receiveWorkerResult({ transportPackage: p, resultRoot: r.resultRoot, referencePath: ref, receivedAt: "2026-01-01T00:00:02.000Z" }); assert.equal(receipt.status, "ACCEPTED"); assert.equal(receipt.trusted, false); });
test("result contract validation occurs before acceptance", () => { const p = dispatchLocalFolder(makePackage({ suffix: "j" }).pkg, path.join(root, "dispatch4")); const r = resultPackage(p, { jobId: "WRONG" }); refreshResultManifest(r); expectCode(() => receiveWorkerResult({ transportPackage: p, resultRoot: r.resultRoot, referencePath: ref }), "WORKER_JOB_ID_MISMATCH"); });
test("corrupt package rejection", () => { const p = makePackage({ suffix: "k" }).pkg; fs.appendFileSync(path.join(p.root, "BLENDER_WORKER_JOB.json"), "corrupt"); expectCode(() => dispatchLocalFolder(p, path.join(root, "dispatch5")), "TRANSPORT_CHECKSUM_MISMATCH"); });
test("corrupt returned artifact rejection", () => { const p = dispatchLocalFolder(makePackage({ suffix: "l" }).pkg, path.join(root, "dispatch6")); const r = resultPackage(p); fs.appendFileSync(path.join(r.resultRoot, "artifacts", "BLENDER_RENDER.png"), "corrupt"); expectCode(() => receiveWorkerResult({ transportPackage: p, resultRoot: r.resultRoot, referencePath: ref }), "WORKER_ARTIFACT_CHECKSUM_FAIL"); });
test("missing returned artifact rejection", () => { const p = dispatchLocalFolder(makePackage({ suffix: "m" }).pkg, path.join(root, "dispatch7")); const r = resultPackage(p); fs.unlinkSync(path.join(r.resultRoot, "artifacts", "BLENDER_RENDER.png")); expectCode(() => receiveWorkerResult({ transportPackage: p, resultRoot: r.resultRoot, referencePath: ref }), "WORKER_ARTIFACT_MISSING"); });
test("wrong workerJobId rejection", () => { const p = dispatchLocalFolder(makePackage({ suffix: "n" }).pkg, path.join(root, "dispatch8")); const r = resultPackage(p, { jobId: "WRONG" }); expectCode(() => receiveWorkerResult({ transportPackage: p, resultRoot: r.resultRoot, referencePath: ref }), "WORKER_JOB_ID_MISMATCH"); });
test("wrong asset rejection", () => { const p = dispatchLocalFolder(makePackage({ suffix: "o" }).pkg, path.join(root, "dispatch9")); const r = resultPackage(p, { assetId: "WRONG" }); expectCode(() => receiveWorkerResult({ transportPackage: p, resultRoot: r.resultRoot, referencePath: ref }), "WORKER_ASSET_ID_MISMATCH"); });
test("wrong recipe rejection", () => { const p = dispatchLocalFolder(makePackage({ suffix: "p" }).pkg, path.join(root, "dispatch10")); const r = resultPackage(p, { recipeId: "WRONG" }); expectCode(() => receiveWorkerResult({ transportPackage: p, resultRoot: r.resultRoot, referencePath: ref }), "WORKER_RECIPE_ID_MISMATCH"); });
test("wrong source build rejection", () => { const p = dispatchLocalFolder(makePackage({ suffix: "q" }).pkg, path.join(root, "dispatch11")); const r = resultPackage(p); r.result.sourceChecksum = "WRONG"; fs.writeFileSync(path.join(r.resultRoot, "BLENDER_WORKER_RESULT.json"), JSON.stringify(r.result)); refreshResultManifest(r); expectCode(() => receiveWorkerResult({ transportPackage: p, resultRoot: r.resultRoot, referencePath: ref }), "WORKER_SOURCE_CHECKSUM_MISMATCH"); });
test("wrong camera rejection", () => { const p = dispatchLocalFolder(makePackage({ suffix: "r" }).pkg, path.join(root, "dispatch12")); const r = resultPackage(p); r.result.cameraValidation.id = "WRONG"; fs.writeFileSync(path.join(r.resultRoot, "BLENDER_WORKER_RESULT.json"), JSON.stringify(r.result)); refreshResultManifest(r); expectCode(() => receiveWorkerResult({ transportPackage: p, resultRoot: r.resultRoot, referencePath: ref }), "WORKER_CAMERA_MISMATCH"); });
test("wrong module identity rejection", () => { const p = dispatchLocalFolder(makePackage({ suffix: "s" }).pkg, path.join(root, "dispatch13")); const r = resultPackage(p); r.result.modules[0].moduleId = "WRONG"; fs.writeFileSync(path.join(r.resultRoot, "BLENDER_WORKER_RESULT.json"), JSON.stringify(r.result)); refreshResultManifest(r); expectCode(() => receiveWorkerResult({ transportPackage: p, resultRoot: r.resultRoot, referencePath: ref }), "WORKER_MODULE_IDENTITY_MISMATCH"); });
test("duplicate receipt is idempotent", () => { const p = dispatchLocalFolder(makePackage({ suffix: "t" }).pkg, path.join(root, "dispatch14")); const r = resultPackage(p); const first = receiveWorkerResult({ transportPackage: p, resultRoot: r.resultRoot, referencePath: ref, receivedAt: "2026-01-01T00:00:02.000Z" }); const second = receiveWorkerResult({ transportPackage: p, resultRoot: r.resultRoot, referencePath: ref, receivedAt: "2026-01-01T00:00:03.000Z" }); assert.equal(first.resultChecksum, second.resultChecksum); assert.equal(second.duplicate, true); });
test("retry safety preserves transport and worker identity", () => { const p = makePackage({ suffix: "u" }).pkg; const retry = dispatchLocalFolder(p, path.join(root, "dispatch15")); assert.equal(retry.envelope.transportJobId, p.envelope.transportJobId); assert.equal(retry.envelope.workerJobId, p.envelope.workerJobId); });
test("expiry rejection", () => { const p = dispatchLocalFolder(makePackage({ suffix: "v" }).pkg, path.join(root, "dispatch16")); p.envelope.expiresAt = "2020-01-01T00:00:00.000Z"; const r = resultPackage(p); expectCode(() => receiveWorkerResult({ transportPackage: p, resultRoot: r.resultRoot, referencePath: ref, receivedAt: "2026-01-01T00:00:00.000Z" }), "TRANSPORT_JOB_EXPIRED"); });
test("accepted render enters existing raster, component and comparison pipeline", () => { const p = dispatchLocalFolder(makePackage({ suffix: "w" }).pkg, path.join(root, "dispatch17")); const r = resultPackage(p); const comparisonInput = { reference: { state: "APPROVED_GOLDEN_REFERENCE", assetId: "ASSET-001", referenceId: "REF-001", version: "1.0.0", checksum: referenceChecksum }, spec: { assetId: "ASSET-001", referenceId: "REF-001", referenceVersion: "1.0.0", sourceImage: { checksum: referenceChecksum } }, componentMap: { components: [] }, palette: {}, camera: { id: "CAM-001", projection: "ORTHOGRAPHIC_LOCKED" }, category: "BUILDING", assetVersion: "1.0.0", buildId: "BUILD-001", iteration: 1 }; const receipt = receiveWorkerResult({ transportPackage: p, resultRoot: r.resultRoot, referencePath: ref, comparisonInput, componentInput: { componentMap: { components: [] }, actualComponents: {} } }); assert.equal(receipt.raster.analysis.ok, true); assert.equal(receipt.raster.components.components.length, 0); assert.equal(receipt.raster.comparison.result, "PASS"); });
test("one-iteration preservation", () => { const p = dispatchLocalFolder(makePackage({ suffix: "x" }).pkg, path.join(root, "dispatch18")); const r = resultPackage(p); const receipt = receiveWorkerResult({ transportPackage: p, resultRoot: r.resultRoot, referencePath: ref }); assert.equal(receipt.localValidation.ok, true); });
test("arbitrary executable script is rejected from manifests", () => { const script = path.join(root, "bad.py"); fs.writeFileSync(script, "print(1)"); const j = job(); expectCode(() => createArtifactManifest({ artifacts: [{ logicalId: "SCRIPT", filename: "bad.py", sourcePath: script, artifactType: "PYTHON_SCRIPT" }] }), "TRANSPORT_PACKAGE_INVALID"); });
