import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs"; import os from "node:os"; import path from "node:path";
import { compareReference, buildCorrectionPlan, detectRegression, writeComparisonPackage } from "../asset-factory/golden-reference/golden-reference-comparison-engine.mjs";
const png=Buffer.from('89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000d49444154789c6360f8cfc000000301010018dd8db00000000049454e44ae426082','hex');
function fixture(){const d=fs.mkdtempSync(path.join(os.tmpdir(),'compare-'));const a=path.join(d,'a.png'),b=path.join(d,'b.png');fs.writeFileSync(a,png);fs.writeFileSync(b,png);const ref={assetId:'TREE',referenceId:'REF',version:'v1',checksum:'x',state:'APPROVED_GOLDEN_REFERENCE'};const spec={assetId:'TREE',referenceId:'REF',referenceVersion:'v1',sourceImage:{checksum:'x'},gameplayCamera:{id:'CAM',projection:'ORTHO'}};return {d,a,b,reference:ref,spec,palette:{},componentMap:{components:[{id:'TRUNK',x:.5,y:.5,width:.1,height:.5}]},componentMapPath:'fixture'};}
test('comparison rejects camera and identity mismatches',()=>{const f=fixture();assert.equal(compareReference({...f,referencePath:f.a,renderPath:f.b,camera:{id:'BAD'},componentMap:f.componentMap}).errorCode,'CAMERA_ALIGNMENT_FAIL');});
test('comparison reports silhouette and protects passing components',()=>{const f=fixture();const c=compareReference({...f,referencePath:f.a,renderPath:f.b,camera:{id:'CAM',projection:'ORTHO'},componentMap:f.componentMap,silhouetteIoU:.4,actualComponents:{TRUNK:{x:.5,y:.5,width:.1,height:.5}}});assert.equal(c.result,'FAIL');assert.deepEqual(c.components.protectedComponents,['TRUNK']);assert.equal(buildCorrectionPlan(c).overallIssues[0].type,'OVERALL_SILHOUETTE_FAIL');});
test('correction plan and regression detection are deterministic',()=>{const f=fixture();const c=compareReference({...f,referencePath:f.a,renderPath:f.b,camera:{id:'CAM',projection:'ORTHO'},componentMap:f.componentMap,silhouetteIoU:1,actualComponents:{TRUNK:{x:.5,y:.5,width:.1,height:.5}}});assert.equal(c.result,'PASS');assert.equal(detectRegression(c,{...c,components:{...c.components,protectedComponents:[]}}).regression,true);const out=path.join(f.d,'pkg');const p=writeComparisonPackage({input:{...f,referencePath:f.a,renderPath:f.b},comparison:c,outputDir:out});assert.equal(p.files.includes('CORRECTION_PLAN.json'),true);});
