import AppKit
let a=CommandLine.arguments;guard a.count==3 else{fatalError("usage output reference")};let rep=NSBitmapImageRep(bitmapDataPlanes:nil,pixelsWide:1800,pixelsHigh:760,bitsPerSample:8,samplesPerPixel:4,hasAlpha:true,isPlanar:false,colorSpaceName:.deviceRGB,bytesPerRow:0,bitsPerPixel:0)!;let c=NSGraphicsContext(bitmapImageRep:rep)!;NSGraphicsContext.saveGraphicsState();NSGraphicsContext.current=c;NSColor(calibratedWhite:0.055,alpha:1).setFill();NSBezierPath(rect:NSRect(x:0,y:0,width:1800,height:760)).fill()
let h:[NSAttributedString.Key:Any]=[.font:NSFont.boldSystemFont(ofSize:31),.foregroundColor:NSColor(calibratedRed:0.95,green:0.9,blue:0.8,alpha:1)],l:[NSAttributedString.Key:Any]=[.font:NSFont.boldSystemFont(ofSize:18),.foregroundColor:NSColor(calibratedRed:0.95,green:0.9,blue:0.8,alpha:1)]
func t(_ s:String,_ x:CGFloat,_ y:CGFloat,_ q:[NSAttributedString.Key:Any]=l){s.draw(at:NSPoint(x:x,y:y),withAttributes:q)};func im(_ p:String,_ r:NSRect,_ al:CGFloat=1){NSImage(contentsOfFile:p)?.draw(in:r,from:.zero,operation:.sourceOver,fraction:al,respectFlipped:false,hints:nil)};func fill(_ r:NSRect,_ c:NSColor){c.setFill();NSBezierPath(rect:r).fill()}
func grid(_ x:CGFloat){let ox=x,oy:CGFloat=100,sc:CGFloat=2.2;NSColor.systemCyan.withAlphaComponent(0.6).setStroke();for q:CGFloat in [0,8,10,231,233,239,247]{let p=NSBezierPath();p.move(to:NSPoint(x:ox+q*sc,y:oy));p.line(to:NSPoint(x:ox+q*sc,y:oy+490));p.stroke()};NSColor.systemOrange.withAlphaComponent(0.6).setStroke();for q:CGFloat in [0,15,23,190,206,222]{let p=NSBezierPath();p.move(to:NSPoint(x:ox,y:oy+490-q*sc));p.line(to:NSPoint(x:ox+545,y:oy+490-q*sc));p.stroke()}}
func structural(_ x:CGFloat){let y:CGFloat=100,sc:CGFloat=2.2;fill(NSRect(x:x,y:y,width:247*sc,height:222*sc),NSColor(calibratedRed:0.72,green:0.57,blue:0.38,alpha:1));fill(NSRect(x:x+10*sc,y:y+32*sc,width:221*sc,height:167*sc),NSColor(calibratedRed:0.03,green:0.22,blue:0.27,alpha:1));fill(NSRect(x:x+8*sc,y:y+30*sc,width:225*sc,height:171*sc),.black);fill(NSRect(x:x+10*sc,y:y+32*sc,width:221*sc,height:167*sc),NSColor(calibratedRed:0.04,green:0.30,blue:0.35,alpha:1));fill(NSRect(x:x,y:y,width:247*sc,height:16*sc),NSColor(calibratedRed:0.76,green:0.62,blue:0.43,alpha:1))}
t("SHOP WINDOW V1 — SHARED GRID + HYBRID PREFLIGHT (2D ONLY)",40,700,h);let xs:[CGFloat]=[40,480,920,1360];let labels=["REFERENCE + GUIDES","MEASURED STRUCTURE","REFERENCE-LAYERED PREFLIGHT","50% OVERLAY"]
for i in 0..<4{t(labels[i],xs[i],640)};im(a[2],NSRect(x:40,y:100,width:545,height:490));grid(40);structural(480);grid(480);im(a[2],NSRect(x:920,y:100,width:545,height:490));grid(920);im(a[2],NSRect(x:1360,y:100,width:545,height:490),0.5);structural(1360);grid(1360)
t("VISION: SAME WINDOW = YES • OWNERSHIP = PASS • GLASS / CASING / HEAD / SILL / APRON / DISPLAY / OPEN SIGN = PASS",40,35)
NSGraphicsContext.restoreGraphicsState();try! rep.representation(using:.png,properties:[:])!.write(to:URL(fileURLWithPath:a[1]))
