import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const {parseSafeFirestoreEmulatorHost}=require('../lib/infrastructure/pins/firestoreEmulatorHost.js');

test('introduction services: saved stages, cotton race, nest and exact hatch boundary',async t=>{
 const host=parseSafeFirestoreEmulatorHost(process.env.FIRESTORE_EMULATOR_HOST);
 if(!host){t.skip('Requires localhost emulator; never contacts live accounts');return;}
 process.env.FIRESTORE_EMULATOR_HOST=host.normalizedHostPort;
 const {initializeApp,deleteApp}=require('firebase-admin/app');const {getFirestore}=require('firebase-admin/firestore');
 const app=initializeApp({projectId:`demo-leonard-${process.pid}`},`leonard-${process.pid}`),db=getFirestore(app);
 t.after(async()=>{await db.terminate();await deleteApp(app);});
 const {startLeonardPilot:start}=require('../lib/domain/quests/leonardStart.js');
 const {commitLeonardProgress:commit}=require('../lib/domain/quests/leonardProgressTransaction.js');
 const {hatchLeonardDove:hatch}=require('../lib/domain/quests/leonardHatch.js');
 const who={uid:'LkR8ugTK6lXGFfUlLvKSiqMoMBh1',email:'godspeed1074@gmail.com',emailVerified:true};
 const origin={latitude:-38.45,longitude:145.24};
 // Synthetic trusted evidence: this tests transactions, not real-map discovery.
 const point=id=>({id,...origin,safe:true});
 const pins=prefix=>Array.from({length:6},(_,i)=>({...point(prefix+i),previouslyCapturedByPlayer:true}));
 const evidence={churches:[{...point('church'),basePins:pins('egg')}],parks:[{...point('park'),basePins:pins('stick')}],shops:[point('shop')]};
 const player=db.collection('players').doc(who.uid),quest=db.collection('leonardIntroductionPlayers').doc(who.uid);
 const legacy=db.collection('birdQuestPlayers').doc(who.uid),inventory=db.collection('playerMarketInventories').doc(who.uid);
 await player.set({profileComplete:true,coins:500,xp:1234});
 await legacy.set({bird:{id:'existing-test-dove',xp:77}});await inventory.set({items:{wheat:19}});
 const begins=await Promise.all([start(db,who,origin,async()=>evidence,true),start(db,who,origin,async()=>evidence,true)]);
 assert.equal(begins.filter(r=>r.started).length,1);assert.equal(begins[0].run.runId,begins[1].run.runId);
 const runId=begins[0].run.runId,input={uid:who.uid,runId};
 const send=(stage,kind,extra={},verify=async()=>{})=>commit(db,{...input,action:{stage,kind,...extra}},verify,()=>100000);
 await assert.rejects(send('meet-leonard','talk',{},async()=>{throw Error('Out of range');}));
 assert.equal((await quest.get()).data().stage,'meet-leonard');
 await send('meet-leonard','talk');
 await assert.rejects(send('lost-eggs','collect-egg',{pinId:'not-your-egg'}));
 for(let i=0;i<6;i++)await send('lost-eggs','collect-egg',{pinId:`egg${i}`});
 await send('return-eggs','talk');await send('return-eggs','talk');
 assert.equal((await quest.get()).data().egg,1);
 const resumed=await start(db,who,origin,async()=>{throw Error('Must not relocate on resume');},true);
 assert.equal(resumed.run.stage,'materials');assert.equal(resumed.run.runId,runId);
 await assert.rejects(send('materials','talk'));
 await player.update({coins:299});await assert.rejects(send('materials','buy-cotton'));
 assert.equal((await quest.get()).data().cotton,0);
 await player.update({coins:500});
 await Promise.all([send('materials','buy-cotton'),send('materials','buy-cotton')]);
 assert.equal((await player.get()).data().coins,200);assert.equal((await quest.get()).data().cotton,6);
 for(let i=0;i<6;i++)await send('materials','collect-stick',{pinId:`stick${i}`});
 await send('materials','collect-stick',{pinId:'stick0'});
 await send('materials','talk');
 await Promise.all([send('craft','craft-nest'),send('craft','craft-nest')]);
 let saved=(await quest.get()).data();assert.equal(saved.nest,1);assert.equal(saved.sticks,0);assert.equal(saved.cotton,0);
 assert.equal(saved.hatchAt,null);
 await Promise.all([send('use','use-nest'),send('use','use-nest')]);
 saved=(await quest.get()).data();assert.equal(saved.hatchAt,100000+86400000);assert.equal(saved.egg,0);assert.equal(saved.nest,0);
 await assert.rejects(hatch(db,input,async()=>{},()=>saved.hatchAt-1));
 const hatches=await Promise.all([hatch(db,input,async()=>{},()=>saved.hatchAt),hatch(db,input,async()=>{},()=>saved.hatchAt)]);
 assert.equal(hatches.filter(r=>r.awarded).length,1);
 assert.equal((await quest.get()).data().stage,'completed');
 assert.equal((await db.collection('playerBirdhouses').doc(who.uid).collection('birds').get()).size,1);
 assert.deepEqual((await legacy.get()).data(),{bird:{id:'existing-test-dove',xp:77}});
 assert.deepEqual((await inventory.get()).data(),{items:{wheat:19}});
 const {updatedAt,...savedPlayer}=(await player.get()).data();
 assert.equal(updatedAt.toMillis(),100000);
 assert.deepEqual(savedPlayer,{profileComplete:true,coins:200,xp:1234});
});
