import test from 'node:test';import assert from 'node:assert/strict';import {createRequire}from'node:module';
const require=createRequire(import.meta.url);
test('mail collection: 200m range, wrong owner, full bag and concurrent retry',async t=>{
 const {parseSafeFirestoreEmulatorHost}=require('../lib/infrastructure/pins/firestoreEmulatorHost.js');
 const host=parseSafeFirestoreEmulatorHost(process.env.FIRESTORE_EMULATOR_HOST);if(!host){t.skip('Local emulator only');return;}
 Object.assign(process.env,{FIRESTORE_EMULATOR_HOST:host.normalizedHostPort,GROWGO_DEVELOPMENT_INVITED_ALPHA_ENFORCED:'false',GROWGO_ACTIVE_DEVICE_SESSION_ENFORCED:'false'});
 const {initializeApp,deleteApp}=require('firebase-admin/app'),{getFirestore,Timestamp}=require('firebase-admin/firestore');
 const app=initializeApp({projectId:`demo-mail-${process.pid}`}),db=getFirestore(app);t.after(async()=>{await db.terminate();await deleteApp(app);});
 const {playerMailHandler:handle}=require('../lib/api/playerMail.js');
 const {buildDefaultPlayerDocument}=require('../lib/domain/players/playerStore.js');
 const {sharedWorldDocumentId}=require('../lib/domain/world/sharedWorld.js');
 const uid='mail-test',postOfficeId='poi:osm:node:123',mailId='test-delivery';
 const owner=db.collection('birdQuestPlayers').doc(uid),letter=owner.collection('mail').doc(mailId),bag=db.collection('playerMarketInventories').doc(uid),player=db.collection('players').doc(uid);
 await player.set({...buildDefaultPlayerDocument(Timestamp.now()),profileComplete:true,displayName:'Mail Tester',gender:'male',country:'Australia',region:'oceania',state:'Victoria',xp:50});
 await owner.set({pendingMailCount:1});await bag.set({schemaVersion:1,items:{wheat:3}});
 await letter.set({schemaVersion:1,status:'unclaimed',reward:{xp:100,points:100,items:{wheat:2}}});
 await db.collection('sharedPoiPins').doc(sharedWorldDocumentId(postOfficeId)).set({id:postOfficeId,type:'poi',subcategory:'Post Office',lat:0,lng:0});
 const call=(data,user=uid)=>handle({auth:{uid:user,token:{email_verified:true}},data});
 const request={action:'collect',mailId,postOfficeId,latitude:0,longitude:0,accuracyMetres:5};
 assert.equal((await call({action:'list'})).letters.length,1);
 await assert.rejects(call({...request,latitude:0.002}),{code:'failed-precondition'});
 await assert.rejects(call(request,'other'),{code:'not-found'});
 await bag.set({items:{wheat:10000}});await assert.rejects(call(request),{code:'failed-precondition'});
 assert.equal((await letter.get()).data().status,'unclaimed');assert.equal((await player.get()).data().xp,50);
 await bag.set({items:{wheat:3}});
 const claims=await Promise.all([call(request),call(request)]);assert.equal(claims.filter(r=>r.collectedNow).length,1);
 assert.equal((await player.get()).data().xp,150);assert.equal((await bag.get()).data().items.wheat,5);
 assert.equal((await owner.get()).data().pendingMailCount,0);assert.equal((await letter.get()).data().status,'claimed');
 const gift=owner.collection('mail').doc('thank-you');
 await gift.set({schemaVersion:1,campaignId:'thank-you',title:'Thank you',message:'thank you so much!',status:'unclaimed',reward:{xp:0,points:0,coins:500,items:{battered_fish:5,wheat_seed:2}}});
 const listed=(await call({action:'list'})).letters.find(l=>l.id==='thank-you');
 assert.equal(listed.message,'thank you so much!');assert.equal(listed.reward.coins,500);
 const giftRequest={...request,mailId:'thank-you'};
 const gifts=await Promise.all([call(giftRequest),call(giftRequest)]);
 assert.equal(gifts.filter(r=>r.collectedNow).length,1);
 assert.equal((await player.get()).data().coins,500);assert.equal((await player.get()).data().xp,150);
 assert.equal((await bag.get()).data().items.battered_fish,5);assert.equal((await bag.get()).data().items.wheat_seed,2);
 assert.equal((await owner.get()).data().pendingMailCount,0);
 const bad=owner.collection('mail').doc('invalid-coins');
 await bad.set({schemaVersion:1,status:'unclaimed',reward:{xp:0,points:0,coins:-1,items:{battered_fish:5}}});
 await assert.rejects(call({...request,mailId:'invalid-coins'}),{code:'failed-precondition'});
 assert.equal((await bad.get()).data().status,'unclaimed');assert.equal((await player.get()).data().coins,500);
 const mailbox=db.collection('personalMailboxes').doc(uid);
 await assert.rejects(call({action:'deployMailbox',latitude:0,longitude:0,accuracyMetres:5}),{code:'permission-denied'});
 await mailbox.set({schemaVersion:1,owned:true,deployed:null});
 assert.equal((await call({action:'status'},'other')).mailbox,null);
 const deployment={action:'deployMailbox',latitude:0,longitude:0,accuracyMetres:5};
 await call(deployment);
 await assert.rejects(call(deployment),{code:'failed-precondition'});
 await assert.rejects(call({action:'packMailbox'},'other'),{code:'permission-denied'});
 const personalLetter=owner.collection('mail').doc('personal-delivery');
 await personalLetter.set({schemaVersion:1,status:'unclaimed',reward:{xp:0,points:0,coins:1,items:{wheat:1}}});
 const personalRequest={...request,mailId:'personal-delivery',postOfficeId:`personal-mailbox:${uid}`};
 await assert.rejects(call({...personalRequest,latitude:0.002}),{code:'failed-precondition'});
 await assert.rejects(call({...personalRequest,postOfficeId:'personal-mailbox:other'}),{code:'failed-precondition'});
 await call(personalRequest);assert.equal((await player.get()).data().coins,501);
 assert.equal((await call({...request,mailId:'personal-delivery'})).collectedNow,false);
 await call({action:'packMailbox'});assert.equal((await mailbox.get()).data().deployed,null);
 await assert.rejects(call(personalRequest),{code:'failed-precondition'});
 await call({...deployment,latitude:1,longitude:1});assert.equal((await mailbox.get()).data().deployed.lat,1);
});
